version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0-disco

    working_directory: /tmp

    steps:
      - checkout
      
      - store_artifacts:
        path: /tmp
        destination: /src

      - run:
          name: Restore
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build -o /tmp/app

      - store_artifacts:
        path: /tmp/app
        destination: /app