version: 2

executors:
  sdk-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0-disco
    working_directory: /src

jobs:
  build:
    executor: sdk-executor

    steps:
      - checkout
      
      - store_artifacts:
          path: /src
          destination: /src

      - run:
          name: Restore
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build -o /src/build

      - persist_to_workspace:
          root: /src
          path: build

  test:
      - attach_workspace:
          at: /src/build
      - run:
          name: Test
          command: dotnet test

  publish:
      - run:
          name: Publish
          command: dotnet publish -o /src/app

      - store_artifacts:
          path: /src/app
          destination: /app

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            -  build
      - publish:
          requires:
            -  test